[
  {
    "name" => "New York City",
    "introduction" => "Cool, cosmopolitan, crowded, constantly evolving… the Big Apple blends big city splendor with small-town charm. Amid Gotham's iconic landmarks and towering skyscrapers, you'll experience a vibrant culture permeating each of the city's distinctive neighborhoods and boroughs. Follow trendsetters to the East Village and Brooklyn to check out indie boutiques, iconic bakeries and trendy coffee shops. Afterward, peruse the racks of the sleek shops lining Fifth Avenue, admire the cutting-edge art collections at the MoMa and the Met, catch a memorable show on Broadway or sit down for a meal at the latest \"it\" restaurant.\n As the most populous city in the U.S. – set at the forefront of food, fashion and the arts – NYC requires stamina. But don't let the Big Apple's frenetic sights and sounds intimidate you from soaking up its grandeur. Wander through the concrete jungle and you'll discover roaring taxis zipping down bustling blocks, fast-paced pedestrians strolling past on their way to marquee galleries and trendy cocktail bars, and Times Square's neon lights flickering at all hours. And yet, the city's twinkling lights and chaotic corners also invite you to embrace every New York minute, explore every enclave and create your own urban adventure. There are endless ways to spend your time in the city that never sleeps, but before you leave, stop and look around – what's here today will be transformed into something bigger and better tomorrow.",
    "cover_url" => "https://travel.usnews.com/static-travel/images/destinations/44/main_image_september_2013.jpg"
  },
  {
    "name" => "San Francisco",
    "introduction" => "A jumbled collage of colorful neighborhoods and beautiful views, San Francisco draws those free-spirited types who have an eye for edgy art, a taste for imaginative cuisine and a zeal for adventure. It's really not surprising that songwriter Tony Bennett left his heart here: The city boasts jaw-dropping sights, world-class cuisine, cozy cafes and plenty of booming nightlife venues – there's no shortage of ways to stay busy here. Spend an hour or two sunning yourself alongside sea lions on the bay, admiring the views of the city from Twin Peaks, or strolling along the Marina. And for the quintessential San Franciscan experience, enjoy a ride on a cable car.\nOften described as Los Angeles' more refined northern cousin, cool and compact San Francisco takes the big-city buzz exuded by its southern counterpart and melds it with a sense of small-town charm. Here, you'll discover a patchwork of culture flourishing throughout San Francisco's many vibrant quarters. Follow the crowds to the touristy Fisherman's Wharf area (which offers spectacular views of Alcatraz) before heading along the bay to the Presidio for a glimpse of the famous Golden Gate Bridge. But don't forget to save time for the Mission district, The Haight and The Castro for exposure to all of the different varieties of the San Francisco lifestyle.",
    "cover_url" => "https://travel.usnews.com/static-travel/images/destinations/20/gettyimages-123318669.jpg"
  },
  {
    "name" => "Washington, D.C.",
    "introduction" => "With its marbled monuments and high-profile politicos, Washington, D.C., has long been saddled with a reputation as a stuffy government-driven town. A \"city of southern efficiency and northern charm,\" as John F. Kennedy once described it, Washington is often seen by outsiders as slow and inefficient. But these days, our nation's capital is awash with a new energy, transforming itself into an exciting, faster-paced East Coast vacation destination. Although the government is still the sun around which this city orbits, the District also offers a host of renowned museums and interesting neighborhoods. And with a recent explosion of restaurants, cafes, boutiques and clubs, D.C. is transitioning into a thriving cultural hub. As the D.C. Tourism Board is emphasizing through its DC Cool campaign, this isn't the Washington you remember from your middle school field trip – it's much hipper than that.\nYou can choose a traditional D.C. adventure, filled with tours of classic attractions like the White House and the Washington Monument, the U.S. Capitol and the Smithsonian National Museum of Natural History. And there's no better way to experience iconic D.C. than with a stroll around the Tidal Basin. (Plan to visit in late March or early April – just in time for the National Cherry Blossom Festival – and you'll be rewarded with a canopy of beautiful pink blooms.) But if you've already seen the national landmarks, get a feel for the city's more youthful ambiance, highlighted by its urban neighborhoods, marquee art galleries and vibrant farmers markets. While you'll only need a few days to see the city as you know it from your history book, it could take months to experience the Washington that today's locals know and love.",
    "cover_url" => "https://travel.usnews.com/static-travel/images/destinations/48/lincoln_memorial_and_reflecting_pool.jpg"
  },
  {
    "name" => "New Orleans",
    "introduction" => "New Orleans is known for its European-style architecture, mouth-watering Creole cuisine and all-around mysticism. And as its backbone is music: Jazz, blues, rock 'n' roll and Zydeco tunes ooze from every city crevice. But for many, the main reason to visit is Mardi Gras, an over-the-top party with Carnaval traits, such as masks, music and an all-around wild time. Even if you don't make it to Mardi Gras, you'll still find a party year-round, with revelers pouring out of Bourbon Street clubs until the wee hours of the morning.\nDespite past environmental disasters — namely the BP Oil Spill, Hurricane Katrina and Hurricane Isaac — New Orleans continues to thrive. Over the past several years, major efforts have been made to restore the distinct districts. Today, the Crescent City looks almost as good as new. So start your visit in the French Quarter, where colonial heritage still survives. From here, you can explore the major architectural sites before enjoying a hearty plate of jambalaya and a rowdy evening out.",
    "cover_url" => "https://travel.usnews.com/static-travel/images/destinations/3/french_quarter_new.jpg"
  },
  {
    "name" => "Los Angeles",
    "introduction" => "Los Angeles both confirms and dismantles all of its stereotypes. Sure, it's a sprawling metropolis with eternally congested freeways, but it also contains one of the most diverse and unique sets of neighborhoods in the United States. La-La Land is filled to the brim with the glamour of chic Hollywood name brands and movie set backdrops, yet it's also home to renowned art galleries like the Los Angeles County Museum of Art and architectural masterpieces like the Getty Center. The world's visual entertainment empire, LA offers tourists behind-the-scenes looks into the world of filmmaking and television broadcasting at studios like Paramount Pictures Studios and Warner Bros. Studio. What's more, the City of Angels features some of the country's most eclectic cuisine and dozens of highly acclaimed restaurants. Away from the revitalized downtown area, the Malibu and Santa Monica beaches provide sun, sand and surfing, while Venice Beach offers close-ups of the city's most unique residents. \n At more than 500 square miles, Los Angeles is massive and touring it can be exhausting – but that doesn't deter visitors. The area is one of the most visited in the country, especially between June and October when thousands of travelers try to get to as many of the spread-out attractions as they can. But the key to a successful L.A. vacation is simple: Plan ahead. Pick a few areas that best suit your interests and needs. Then all that's left to do is explore, explore, explore.",
    "cover_url" => "https://travel.usnews.com/static-travel/images/destinations/18/gettyimages-500726091.jpg"
  },
  {
    "name" => "Seattle",
    "introduction" => "Seattle's laid-back attitude and diverse neighborhoods more than make up for its consistently cloudy weather. Plus, it's home to some of the country's best coffee and a thriving arts scene, plenty of history, culture and – when the weather permits – some exciting outdoor activities. Surrounded by water (and resting between Puget Sound and Lake Washington), the city's favorite outdoor pursuits include kayaking, hiking and camping. Not only that, but the nearby Olympic Mountains and the giant Mount Rainier are visible from many spots in the city; ski slopes are just a short drive away. And while travelers often bemoan the weather, there's actually less annual precipitation here than in New York or Boston. Overcast skies rarely stop Seattleites from getting out and exploring the city – and it shouldn't stop you either. \nIf you're headed to the Emerald City and not up for strenuous outdoor activities, Seattle still offers plenty to do and see. Art lovers will appreciate the glass-blown pieces at Chihuly Garden and Glass as well as the works on display at the Seattle Art Museum. Maritime enthusiasts can explore the Hiram M. Chittenden Locks and watch the ships putter by. Make time to switch gears from boats to brews on a visit here, too. The city boasts dozens of craft breweries and food markets, making it one of the Best Foodie Destinations in the USA. ",
    "cover_url" => "https://travel.usnews.com/static-travel/images/destinations/21/seattle_sky1_resized.jpg"
  },
  {
    "name" => "Chicago",
    "introduction" => "\"It is hopeless for the occasional visitor to try to keep up with Chicago. She outgrows his prophecies faster than he can make them.\" Although he made up his mind about the Windy City before it even reached its 50th year, Mark Twain's impression of Chicago has proven long-lasting. America's third-largest city has been described in a myriad of ways throughout its lifetime. When Thomas Edison and Nikola Tesla were competing for the right to use their forms of electricity to illuminate the 1893 World's Columbian Exposition (also known as the Chicago World's Fair), Chicago was known as a city of industry. When Prohibition set in, notorious mobsters like Al Capone transformed Chicagoland into their own dangerous playground. And intense immigration surges throughout the 20th century brought a host of new identities to the Windy City, including Greek, Polish, Italian, Irish and Jewish.\nToday, Chicago remains just as diverse, boasting a thriving arts scene, various shopping districts and a cornucopia of eateries. First-time Chi-Town visitors are sure to have their eyes to the sky for at least a day or two. Chicago's skyscrapers and public art are absolutely worth admiring: Tag along on a Chicago Architecture River Cruise or pass a few hours in Millennium Park and you'll find yourself spending lots of time looking upward. For a bird's-eye perspective, head to Willis Tower's Skydeck Chicago or the John Hancock Center's 360 CHICAGO Observation Deck. After, dive headfirst into all the city has to offer – from exceptional museums to a thriving sports culture and deep-dish pizza that takes delicious to whole new depths.",
    "cover_url" => "https://travel.usnews.com/static-travel/images/destinations/2/chicago_getty_jaskoomerovic.jpg"
  },
  {
    "name" => "Boston",
    "introduction" => "Boston – or \"Bahston,\" as the locals say – is not only a hub for baseball, brownstones and bookish collegiate types. It's also home to America's first large free municipal public library, the first subway system, the first public school and the first public park. To say the city is historic would be an understatement, but this wicked smart college town doesn't linger in the past, either. A well-rounded trip to Boston integrates the classic with the contemporary: Split your time between cherished sites like the Paul Revere House and Faneuil Hall and modern attractions like the Museum of Fine Arts. Venture to Beacon Hill and you'll stumble upon the graceful mansions of yore juxtaposed with chic boutiques and innovative hotels. So, yes, come first for the history, but don't miss out on the opportunity to sample the unmistakable Beantown flavor. \nThe city's darker side has garnered a rough-and-tumble reputation thanks to Hollywood appearances in gritty films like Black Mass, American Hustle, and The Town, but Boston's cool, cosmopolitan personality pervades its trendy restaurants, urban parks and modern museums. Passionate residents are still rooting for their beloved Red Sox, but they're also venturing to the Rose Fitzgerald Kennedy Greenway for a free yoga class or meandering to the edgy SoWa Open Market for some antique shopping. So, grab a stool and join them at their favorite pub to chow down on oyster shooters and New England clam chowder, or venture to Back Bay to sip a coffee as you stroll along the trendy Newbury Street. You'll need more than a few days to experience the city's wealth of cultural and historical offerings, but meandering along Boston's cobblestone streets is a great way to start your exploration.",
    "cover_url" => "https://travel.usnews.com/static-travel/images/destinations/23/boston_harbor.jpg"
  },
  {
    "name" => "Orlando",
    "introduction" => "Orlando's pleasant weather, affordable housing, and location at the center of one of the country's fastest growing markets, have helped make the city a boom town. New residents are drawn by the city's attractive setting among the inland lakes and citrus groves and by the short drive from the coastal beaches. Growing numbers of manufacturers and distributors have relocated to the city to take advantage of its mushrooming work force, and major attractions like Walt Disney World, Sea World of Florida, and Universal Studios Florida bring millions of visitors annually. New industries such as film production, military simulation and training, and various technologies are adding to the booming local economy.",
    "cover_url" => "https://www.telegraph.co.uk/content/dam/Travel/leadAssets/32/38/disney-world-flori_3238004a.jpg?imwidth=450"
  }
]
